from app.db import engine
from app.models import Player, PlayerSlate, PlayerSlotEligibility, Sport, ContestType, EligiblePosition
from app.optimizer.compound_slots import get_extra_slots
from sqlmodel import Session

players_data = [
    {
        "name": "Christian McCaffrey",
        "sport": Sport.NFL,
        "team": "SF",
        "real_position": "RB",
        "salary": 9200,
        "projection": 22.1,
        "slots": ["RB"],
    },
    {
        "name": "Josh Allen",
        "sport": Sport.NFL,
        "team": "BUF",
        "real_position": "QB",
        "salary": 8100,
        "projection": 23.4,
        "slots": ["QB"],
    },
    {
        "name": "Patrick Mahomes",
        "sport": Sport.NFL,
        "team": "KC",
        "real_position": "QB",
        "salary": 7900,
        "projection": 21.8,
        "slots": ["QB"],
    },
    {
        "name": "Jalen Hurts",
        "sport": Sport.NFL,
        "team": "PHI",
        "real_position": "QB",
        "salary": 7700,
        "projection": 20.9,
        "slots": ["QB"],
    },
    {
        "name": "Bijan Robinson",
        "sport": Sport.NFL,
        "team": "ATL",
        "real_position": "RB",
        "salary": 7600,
        "projection": 17.5,
        "slots": ["RB"],
    },
    {
        "name": "Breece Hall",
        "sport": Sport.NFL,
        "team": "NYJ",
        "real_position": "RB",
        "salary": 6900,
        "projection": 15.8,
        "slots": ["RB"],
    },
    {
        "name": "Jahmyr Gibbs",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "RB",
        "salary": 6600,
        "projection": 14.9,
        "slots": ["RB"],
    },
    {
        "name": "Rachaad White",
        "sport": Sport.NFL,
        "team": "TB",
        "real_position": "RB",
        "salary": 5200,
        "projection": 11.2,
        "slots": ["RB"],
    },
    {
        "name": "Justin Jefferson",
        "sport": Sport.NFL,
        "team": "MIN",
        "real_position": "WR",
        "salary": 8800,
        "projection": 19.6,
        "slots": ["WR"],
    },
    {
        "name": "CeeDee Lamb",
        "sport": Sport.NFL,
        "team": "DAL",
        "real_position": "WR",
        "salary": 8300,
        "projection": 18.2,
        "slots": ["WR"],
    },
    {
        "name": "Amon-Ra St. Brown",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "WR",
        "salary": 7900,
        "projection": 17.4,
        "slots": ["WR"],
    },
    {
        "name": "A.J. Brown",
        "sport": Sport.NFL,
        "team": "PHI",
        "real_position": "WR",
        "salary": 7200,
        "projection": 15.9,
        "slots": ["WR"],
    },
    {
        "name": "DK Metcalf",
        "sport": Sport.NFL,
        "team": "SEA",
        "real_position": "WR",
        "salary": 6400,
        "projection": 13.7,
        "slots": ["WR"],
    },
    {
        "name": "Tank Dell",
        "sport": Sport.NFL,
        "team": "HOU",
        "real_position": "WR",
        "salary": 4900,
        "projection": 10.1,
        "slots": ["WR"],
    },
    {
        "name": "Travis Kelce",
        "sport": Sport.NFL,
        "team": "KC",
        "real_position": "TE",
        "salary": 6800,
        "projection": 14.5,
        "slots": ["TE"],
    },
    {
        "name": "Sam LaPorta",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "TE",
        "salary": 5600,
        "projection": 11.8,
        "slots": ["TE"],
    },
    {
        "name": "Trey McBride",
        "sport": Sport.NFL,
        "team": "ARI",
        "real_position": "TE",
        "salary": 4200,
        "projection": 8.9,
        "slots": ["TE"],
    },
    {
        "name": "49ers",
        "sport": Sport.NFL,
        "team": "SF",
        "real_position": "DST",
        "salary": 3400,
        "projection": 9.8,
        "slots": ["DST"],
    },
    {
        "name": "Ravens",
        "sport": Sport.NFL,
        "team": "BAL",
        "real_position": "DST",
        "salary": 3100,
        "projection": 8.6,
        "slots": ["DST"],
    },
    {
        "name": "Jets",
        "sport": Sport.NFL,
        "team": "NYJ",
        "real_position": "DST",
        "salary": 2300,
        "projection": 6.4,
        "slots": ["DST"],
    },
    {
        "name": "Spencer Rattler",
        "sport": Sport.NFL,
        "team": "NO",
        "real_position": "QB",
        "salary": 5000,
        "projection": 13.2,
        "slots": ["QB"],
    },
    {
        "name": "Tyler Allgeier",
        "sport": Sport.NFL,
        "team": "ATL",
        "real_position": "RB",
        "salary": 4200,
        "projection": 8.9,
        "slots": ["RB"],
    },
    {
        "name": "Xavier Legette",
        "sport": Sport.NFL,
        "team": "CAR",
        "real_position": "WR",
        "salary": 3600,
        "projection": 7.1,
        "slots": ["WR"],
    },
    {
        "name": "Jonnu Smith",
        "sport": Sport.NFL,
        "team": "MIA",
        "real_position": "TE",
        "salary": 2800,
        "projection": 5.4,
        "slots": ["TE"],
    },
    {
        "name": "Titans",
        "sport": Sport.NFL,
        "team": "TEN",
        "real_position": "DST",
        "salary": 2000,
        "projection": 5.1,
        "slots": ["DST"],
    },
    {
        "name": "Nikola Jokic",
        "sport": Sport.NBA,
        "team": "DEN",
        "real_position": "C",
        "salary": 11000,
        "projection": 58.2,
        "slots": ["C"],
    },
    {
        "name": "Luka Doncic",
        "sport": Sport.NBA,
        "team": "DAL",
        "real_position": "PG",
        "salary": 10800,
        "projection": 56.4,
        "slots": ["PG"],
    },
    {
        "name": "Shai Gilgeous-Alexander",
        "sport": Sport.NBA,
        "team": "OKC",
        "real_position": "PG",
        "salary": 10200,
        "projection": 52.1,
        "slots": ["PG"],
    },
    {
        "name": "Giannis Antetokounmpo",
        "sport": Sport.NBA,
        "team": "MIL",
        "real_position": "PF",
        "salary": 10500,
        "projection": 54.8,
        "slots": ["PF"],
    },
    {
        "name": "Jayson Tatum",
        "sport": Sport.NBA,
        "team": "BOS",
        "real_position": "SF",
        "salary": 9600,
        "projection": 47.3,
        "slots": ["SF"],
    },
    {
        "name": "Devin Booker",
        "sport": Sport.NBA,
        "team": "PHX",
        "real_position": "SG",
        "salary": 8800,
        "projection": 43.5,
        "slots": ["SG"],
    },
    {
        "name": "Anthony Davis",
        "sport": Sport.NBA,
        "team": "LAL",
        "real_position": "C",
        "salary": 9200,
        "projection": 46.1,
        "slots": ["C"],
    },
    {
        "name": "Tyrese Haliburton",
        "sport": Sport.NBA,
        "team": "IND",
        "real_position": "PG",
        "salary": 8400,
        "projection": 41.7,
        "slots": ["PG"],
    },
    {
        "name": "Donovan Mitchell",
        "sport": Sport.NBA,
        "team": "CLE",
        "real_position": "SG",
        "salary": 8100,
        "projection": 40.2,
        "slots": ["SG"],
    },
    {
        "name": "Jalen Brunson",
        "sport": Sport.NBA,
        "team": "NYK",
        "real_position": "PG",
        "salary": 7800,
        "projection": 38.9,
        "slots": ["PG"],
    },
    {
        "name": "Paolo Banchero",
        "sport": Sport.NBA,
        "team": "ORL",
        "real_position": "PF",
        "salary": 7500,
        "projection": 37.4,
        "slots": ["PF"],
    },
    {
        "name": "Jaylen Brown",
        "sport": Sport.NBA,
        "team": "BOS",
        "real_position": "SF",
        "salary": 7200,
        "projection": 35.8,
        "slots": ["SF"],
    },
    {
        "name": "Domantas Sabonis",
        "sport": Sport.NBA,
        "team": "SAC",
        "real_position": "C",
        "salary": 6900,
        "projection": 34.6,
        "slots": ["C"],
    },
    {
        "name": "Franz Wagner",
        "sport": Sport.NBA,
        "team": "ORL",
        "real_position": "SF",
        "salary": 5800,
        "projection": 29.1,
        "slots": ["SF"],
    },
    {
        "name": "Coby White",
        "sport": Sport.NBA,
        "team": "CHI",
        "real_position": "SG",
        "salary": 5200,
        "projection": 25.7,
        "slots": ["SG"],
    },
    {
        "name": "Jose Alvarado",
        "sport": Sport.NBA,
        "team": "NOP",
        "real_position": "PG",
        "salary": 3800,
        "projection": 18.2,
        "slots": ["PG"],
    },
    {
        "name": "Gary Payton II",
        "sport": Sport.NBA,
        "team": "GSW",
        "real_position": "SG",
        "salary": 3600,
        "projection": 16.5,
        "slots": ["SG"],
    },
    {
        "name": "Jaden McDaniels",
        "sport": Sport.NBA,
        "team": "MIN",
        "real_position": "SF",
        "salary": 4000,
        "projection": 19.1,
        "slots": ["SF"],
    },
    {
        "name": "Kyle Kuzma",
        "sport": Sport.NBA,
        "team": "MIL",
        "real_position": "PF",
        "salary": 3900,
        "projection": 17.8,
        "slots": ["PF"],
    },
    {
        "name": "Clint Capela",
        "sport": Sport.NBA,
        "team": "ATL",
        "real_position": "C",
        "salary": 3700,
        "projection": 17.3,
        "slots": ["C"],
    },
]

with Session(engine) as session:
    for data in players_data:
        player = Player(
            name=data["name"],
            sport=data["sport"],
            team=data["team"],
            real_position=data["real_position"],
        )
        slate = PlayerSlate(
            player=player,
            site="DraftKings",
            contest_type=ContestType.CLASSIC,
            salary=data["salary"],
            projection=data["projection"],
        )
        for slot in data["slots"]:
            slot_eligibility = PlayerSlotEligibility(
                slot=slot,
                player_slate=slate,
            )
        extra_slots = get_extra_slots("DraftKings", data["sport"].value, data["real_position"])
        for slot in extra_slots:
            slot_eligibility = PlayerSlotEligibility(
                slot=slot,
                player_slate=slate
            )
        
        session.add(player)

    session.commit()