from app.db import engine
from app.models import Player, PlayerSlate, PlayerSlotEligibility, Sport, ContestType, EligiblePosition
from sqlmodel import Session

players_data = [
    {
        "name": "Christian McCaffrey",
        "sport": Sport.NFL,
        "team": "SF",
        "real_position": "RB",
        "salary": 9200,
        "projection": 22.1,
        "slots": ["RB", "FLEX"],
    },
    {
        "name": "Josh Allen",
        "sport": Sport.NFL,
        "team": "BUF",
        "real_position": "QB",
        "salary": 8100,
        "projection": 23.4,
        "slots": ["QB"],
    },
    {
        "name": "Patrick Mahomes",
        "sport": Sport.NFL,
        "team": "KC",
        "real_position": "QB",
        "salary": 7900,
        "projection": 21.8,
        "slots": ["QB"],
    },
    {
        "name": "Jalen Hurts",
        "sport": Sport.NFL,
        "team": "PHI",
        "real_position": "QB",
        "salary": 7700,
        "projection": 20.9,
        "slots": ["QB"],
    },
    {
        "name": "Bijan Robinson",
        "sport": Sport.NFL,
        "team": "ATL",
        "real_position": "RB",
        "salary": 7600,
        "projection": 17.5,
        "slots": ["RB", "FLEX"],
    },
    {
        "name": "Breece Hall",
        "sport": Sport.NFL,
        "team": "NYJ",
        "real_position": "RB",
        "salary": 6900,
        "projection": 15.8,
        "slots": ["RB", "FLEX"],
    },
    {
        "name": "Jahmyr Gibbs",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "RB",
        "salary": 6600,
        "projection": 14.9,
        "slots": ["RB", "FLEX"],
    },
    {
        "name": "Rachaad White",
        "sport": Sport.NFL,
        "team": "TB",
        "real_position": "RB",
        "salary": 5200,
        "projection": 11.2,
        "slots": ["RB", "FLEX"],
    },
    {
        "name": "Justin Jefferson",
        "sport": Sport.NFL,
        "team": "MIN",
        "real_position": "WR",
        "salary": 8800,
        "projection": 19.6,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "CeeDee Lamb",
        "sport": Sport.NFL,
        "team": "DAL",
        "real_position": "WR",
        "salary": 8300,
        "projection": 18.2,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "Amon-Ra St. Brown",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "WR",
        "salary": 7900,
        "projection": 17.4,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "A.J. Brown",
        "sport": Sport.NFL,
        "team": "PHI",
        "real_position": "WR",
        "salary": 7200,
        "projection": 15.9,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "DK Metcalf",
        "sport": Sport.NFL,
        "team": "SEA",
        "real_position": "WR",
        "salary": 6400,
        "projection": 13.7,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "Tank Dell",
        "sport": Sport.NFL,
        "team": "HOU",
        "real_position": "WR",
        "salary": 4900,
        "projection": 10.1,
        "slots": ["WR", "FLEX"],
    },
    {
        "name": "Travis Kelce",
        "sport": Sport.NFL,
        "team": "KC",
        "real_position": "TE",
        "salary": 6800,
        "projection": 14.5,
        "slots": ["TE", "FLEX"],
    },
    {
        "name": "Sam LaPorta",
        "sport": Sport.NFL,
        "team": "DET",
        "real_position": "TE",
        "salary": 5600,
        "projection": 11.8,
        "slots": ["TE", "FLEX"],
    },
    {
        "name": "Trey McBride",
        "sport": Sport.NFL,
        "team": "ARI",
        "real_position": "TE",
        "salary": 4200,
        "projection": 8.9,
        "slots": ["TE", "FLEX"],
    },
    {
        "name": "49ers",
        "sport": Sport.NFL,
        "team": "SF",
        "real_position": "DST",
        "salary": 3400,
        "projection": 9.8,
        "slots": ["DST"],
    },
    {
        "name": "Ravens",
        "sport": Sport.NFL,
        "team": "BAL",
        "real_position": "DST",
        "salary": 3100,
        "projection": 8.6,
        "slots": ["DST"],
    },
    {
        "name": "Jets",
        "sport": Sport.NFL,
        "team": "NYJ",
        "real_position": "DST",
        "salary": 2300,
        "projection": 6.4,
        "slots": ["DST"],
    },
]

with Session(engine) as session:
    for data in players_data:
        player = Player(
            name=data["name"],
            sport=data["sport"],
            team=data["team"],
            real_position=data["real_position"],
        )
        slate = PlayerSlate(
            player=player,
            site="DraftKings",
            contest_type=ContestType.CLASSIC,
            salary=data["salary"],
            projection=data["projection"],
        )
        for slot in data["slots"]:
            slot_eligibility = PlayerSlotEligibility(
                slot=slot,
                player_slate=slate,
            )
        
        session.add(player)

    session.commit()