"""add projection_source and slate_projection tables

Revision ID: 2ff11e09ca24
Revises: 9702330e48b2
Create Date: 2026-07-05 07:21:28.646710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ff11e09ca24'
down_revision: Union[str, Sequence[str], None] = '9702330e48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projection_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slate_projection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_slate_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('projection', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_slate_id'], ['player_slate.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['projection_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slate_projection')
    op.drop_table('projection_source')
    # ### end Alembic commands ###
