"""create player tables

Revision ID: 3da4df4de77a
Revises: 
Create Date: 2026-07-03 05:41:23.511008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3da4df4de77a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sa.Enum('NFL', 'NBA', 'MLB', 'NHL', 'CFB', name='sport'), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('real_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_slate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('site', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contest_type', sa.Enum('CLASSIC', 'TIERS', 'SHOWDOWN', name='contesttype'), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('projection', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_slot_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_slate_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Enum('QB', 'RB', 'WR', 'TE', 'FLEX', 'DST', 'CPT', name='eligibleposition'), nullable=False),
    sa.ForeignKeyConstraint(['player_slate_id'], ['player_slate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_slot_eligibility')
    op.drop_table('player_slate')
    op.drop_table('player')
    # ### end Alembic commands ###
